Fix tests/lint build errors
Snugug/reparo-cli pull request #2
Opened 2017-04-19 20:13 UTC by tay1orjones

Resolves #1

2017-04-19 20:16 UTC, Snugug requested changes

2017-04-19 20:16 UTC, Snugug commented on tests/args.js
> +    t.is(e.message, 'Repository Slug needs to contain user and repo name (e.g. \'snugug/reparo\'). Set to \'snugug\'');
Please revert this back.

2017-04-19 20:20 UTC, tay1orjones commented on tests/args.js
> +    t.is(e.message, 'Repository Slug needs to contain user and repo name (e.g. \'snugug/reparo\'). Set to \'snugug\'');
Tests don't pass with the mismatching messages. Should I change back this and also update the message within `./lib/args.js` as well?

2017-04-25 19:49 UTC, tay1orjones commented
@Snugug please review changes. Tests do not pass without matching messages in `lib/args.js` and `tests/args.js`

2021-02-03 22:57 UTC, closed without merging